/**
 * GENERATED by `npm run build:icons` from public/logo.svg. Do not edit — edit
 * the source and re-run, or the mark drifts from the shipped icons.
 *
 * The four ribbons of the helparr mark, monochrome. The tile, the lime-to-green
 * ramp and the long shadows are all dropped: this variant exists to sit in app
 * chrome, where it inherits `currentColor` from whatever is around it, and a
 * four-step gradient would put a second palette next to the single-accent
 * chrome the rest of the UI is painted in.
 */
import type { SVGProps } from 'react';

/** The mark's own bounding box in source units — see `markGeometry` in the generator. */
const VIEW_BOX = '229 311 566 401';

/** 566 / 401, the mark's aspect ratio. Height follows from the requested width. */
const ASPECT = 566 / 401;

interface BrandMarkProps extends SVGProps<SVGSVGElement> {
  /** Rendered width in px. Height is derived — the mark is wider than it is tall. */
  size?: number;
}

export default function BrandMark({ size = 16, className = '', ...rest }: BrandMarkProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={size}
      height={Number((size / ASPECT).toFixed(2))}
      viewBox={VIEW_BOX}
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
      className={className}
      {...rest}
    >
      <path d="M276 311 L795 311 L763 361 L568 361 C549 361 534 385 515 385 L229 385 Z" />
      <path d="M261 444 L432 444 C448 444 463 420 479 420 L795 420 L763 470 L568 470 C549 470 534 494 515 494 L229 494 Z" />
      <path d="M261 553 L432 553 C448 553 463 529 479 529 L795 529 L763 579 L568 579 C549 579 534 603 515 603 L229 603 Z" />
      <path d="M261 662 L432 662 C448 662 463 638 479 638 L795 638 L763 688 L568 688 C549 688 534 712 515 712 L229 712 Z" />
    </svg>
  );
}
