#!/usr/bin/env node
/**
 * Assembles the published landing site into `.site/`.
 *
 *   npm run site
 *
 * The site's sources are split across three directories for reasons that have
 * nothing to do with the site: `site/` is the page, `docs/screenshots/` is
 * generated by the browser test lane and is also what the README embeds, and
 * `public/logo.svg` is the mark every shipped icon is rendered from. None of
 * the three can move without breaking the thing that actually owns it, so this
 * script is what makes them one tree.
 *
 * It copies. That is the whole design (ADR-10). It substitutes no value,
 * templates no file, and minifies nothing, because three separate checks read
 * its output and treat it as the published artifact:
 *
 *   - `test/site-facts.test.ts`  — every [data-fact] against the repository
 *   - `test/site-links.test.ts`  — every href and src resolves inside the tree
 *   - `test/site-weight.test.ts` — total transfer weight against the baseline
 *
 * plus `.github/workflows/pages.yml`, which uploads it verbatim. A check that
 * compares a value this script had just injected against that value's own
 * source could never fail — it would be asserting that a variable equals
 * itself. Keeping the assembler dumb is what keeps those three honest.
 *
 * `.site/` is build output and gitignored. `site/` is the source and is
 * committed; it deliberately contains no image, so that the screenshots have
 * exactly one home in the repository.
 */

import { cp, mkdir, readdir, rm, stat } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, '.site');

/**
 * Files under `site/` that are notes to whoever maintains the page rather than
 * part of the page. `weight-baseline.json` is the committed size budget —
 * publishing it would both count against the budget it defines and put an
 * internal number on the web — and `README.md` is the maintenance guide, which
 * Pages would happily serve at `/README.md` to nobody's benefit.
 */
const NOT_PUBLISHED = new Set(['weight-baseline.json', 'README.md']);

/**
 * Where each source tree lands in the built site. The destinations are what the
 * markup already references — `./screenshots/…` in the four `<img>` tags and
 * `./logo.svg` in the favicon link — so changing one here means changing
 * `site/index.html` in the same commit, and `site-links` will say so if not.
 */
const SOURCES = [
  { from: 'site', to: '.', filter: (name) => !NOT_PUBLISHED.has(name) },
  { from: 'docs/screenshots', to: 'screenshots' },
  { from: 'public/logo.svg', to: 'logo.svg' },
];

/** Every file in the built tree, relative to `.site/`, with its size. */
async function manifest(dir, prefix = '') {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      files.push(...(await manifest(path.join(dir, entry.name), rel)));
    } else {
      files.push([rel, (await stat(path.join(dir, entry.name))).size]);
    }
  }
  return files;
}

async function main() {
  // Rebuild from empty rather than copying over the last run: a file deleted
  // from `site/` would otherwise survive in `.site/` and keep being published,
  // and the weight check would keep counting it.
  await rm(OUT, { recursive: true, force: true });
  await mkdir(OUT, { recursive: true });

  for (const { from, to, filter } of SOURCES) {
    const source = path.join(ROOT, from);
    const target = path.join(OUT, to);
    await cp(source, target, {
      recursive: true,
      // `cp`'s filter runs on the root too, where basename is the source
      // directory's own name — let that through and only judge its contents.
      filter: filter ? (src) => src === source || filter(path.basename(src)) : undefined,
    });
  }

  const files = await manifest(OUT);
  const total = files.reduce((sum, [, bytes]) => sum + bytes, 0);
  const width = Math.max(...files.map(([file]) => file.length));

  console.log(`site assembled into ${path.relative(ROOT, OUT)}/\n`);
  for (const [file, bytes] of files) {
    console.log(`  ${file.padEnd(width)}  ${String(bytes).padStart(7)} B`);
  }
  console.log(`\n  ${files.length} files, ${total} B raw`);
}

main().catch((error) => {
  console.error(`site build failed — ${error.message}`);
  process.exit(1);
});
